package handler

import (
	"fmt"
	"net/http"
	"server/internal/common/dto"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/sirupsen/logrus"
)

func (h *Handler) signUp(c *gin.Context) {
	op := "handler.auth_handler.singUp"

	log := logrus.WithField("op", op)

	var input dto.SignUpDto

	if err := c.BindJSON(&input); err != nil {
		log.Error(fmt.Sprintf("request body error: %s", err.Error()))
		NewErrorResponse(c, http.StatusBadRequest, err.Error())
		return
	}

	if err := h.Validator.Struct(input); err != nil {
		log.Error(fmt.Sprintf("validate error: %s", err.Error()))
		NewErrorResponse(c, http.StatusBadRequest, err.Error())
		return
	}

	user, err := h.Services.CreateUser(input)
	if err != nil {
		log.Error(fmt.Sprintf("create user error: %s", err.Error()))
		NewErrorResponse(c, http.StatusBadRequest, err.Error())
		return
	}

	log.Info(fmt.Sprintf("user added: %s", user.Id))

	tokens, err := h.Services.GenerateTokenByUser(user)
	if err != nil {
		log.Error(fmt.Sprintf("tokens generate error: %s", err.Error()))
		NewErrorResponse(c, http.StatusInternalServerError, err.Error())
		return
	}

	log.Info(fmt.Sprintf("tokens generated by user: %s", user.Username))

	maxAge := int(time.Until(tokens.RefreshExpires).Seconds())
	h.Services.SetCookie(c, "refresh_token", tokens.RefreshToken, maxAge)

	c.JSON(http.StatusOK, gin.H{
		"auth": &dto.TokenResponse{
			AccessToken:   tokens.AccessToken,
			TokenType:     "Bearer",
			AccessExpires: tokens.AccessExpires,
		},
		"data": user,
	})
}

func (h *Handler) signIn(c *gin.Context) {
	op := "handler.auth_handler.singIn"

	log := logrus.WithField("op", op)

	var input *dto.SignInDto

	if err := c.BindJSON(&input); err != nil {
		log.Error(fmt.Sprintf("request body error: %s", err.Error()))
		NewErrorResponse(c, http.StatusBadRequest, err.Error())
		return
	}

	if err := h.Validator.Struct(input); err != nil {
		log.Error(fmt.Sprintf("validate error: %s", err.Error()))
		NewErrorResponse(c, http.StatusBadRequest, err.Error())
		return
	}

	user, err := h.Services.GetUserByUsernameAndPassword(input.Username, input.Password)
	if err != nil {
		log.Error(fmt.Sprintf("user error in db: %s", err.Error()))
		NewErrorResponse(c, http.StatusBadRequest, err.Error())
		return
	}

	tokens, err := h.Services.GenerateTokenByUser(user)
	if err != nil {
		log.Error(fmt.Sprintf("tokens generate error: %s", err.Error()))
		NewErrorResponse(c, http.StatusBadRequest, err.Error())
		return
	}

	log.Info(fmt.Sprintf("tokens generated by user: %s", input.Username))

	maxAge := int(time.Until(tokens.RefreshExpires).Seconds())
	h.Services.SetCookie(c, "refresh_token", tokens.RefreshToken, maxAge)

	c.JSON(http.StatusOK, gin.H{
		"auth": &dto.TokenResponse{
			AccessToken:   tokens.AccessToken,
			TokenType:     "Bearer",
			AccessExpires: tokens.AccessExpires,
		},
		"data": user,
	})
}

func (h *Handler) Refresh(c *gin.Context) {
	op := "hanler.auth_handler.refresh"

	log := logrus.WithField("op", op)

	value, err := h.Services.GetCookie(c, "refresh_token")
	if err != nil {
		log.Error(fmt.Sprintf("get token error: %s", err.Error()))
		NewErrorResponse(c, http.StatusBadRequest, err.Error())
		return
	}

	claims, err := h.Services.ParseRefreshToken(value)
	if err != nil {
		log.Error(fmt.Sprintf("parse token error: %s", err.Error()))
		NewErrorResponse(c, http.StatusUnauthorized, err.Error())
		return
	}

	userId := claims.UserId
	user, err := h.Services.GetUserById(userId)
	if err != nil {
		log.Error(fmt.Sprintf("User not found: %s", err.Error()))
		NewErrorResponse(c, http.StatusNotFound, err.Error())
		return
	}

	tokens, err := h.Services.GenerateTokenByUser(user)
	if err != nil {
		log.Error(fmt.Sprintf("tokens generate error: %s", err.Error()))
		NewErrorResponse(c, http.StatusInternalServerError, err.Error())
		return
	}

	maxAge := int(time.Until(tokens.RefreshExpires).Seconds())
	h.Services.SetCookie(c, "refresh_token", tokens.RefreshToken, maxAge)

	c.JSON(http.StatusOK, gin.H{
		"auth": &dto.TokenResponse{
			AccessToken:   tokens.AccessToken,
			TokenType:     "Bearer",
			AccessExpires: tokens.AccessExpires,
		},
		"data": user,
	})
}

func (h *Handler) me(c *gin.Context) {
	op := "handler.auth_handler.me"

	log := logrus.WithField("op", op)

	value, ok := c.Get(userCtx)
	if !ok {
		log.Error("invalid user id")
		NewErrorResponse(c, http.StatusBadRequest, "invalid user id")
		return
	}

	userId, ok := value.(string)
	if !ok {
		log.Error("invalid user id")
		NewErrorResponse(c, http.StatusBadRequest, "invalid user id")
		return
	}

	user, err := h.Services.GetUserById(userId)
	if err != nil {
		log.Error(fmt.Sprintf("User not found: %s", err.Error()))
		NewErrorResponse(c, http.StatusNotFound, err.Error())
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"data": user,
	})
}
